title:            Zach Zhang's Website
description:      Welcome to my site.
# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://zzh237.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project
owner:
  name:           Zach Zhang
  avatar:         /author_images/zz.jpg
  bio:            Machine Learning, Artificial Intelligence, Data Science, Intelligent Agriculture. On the Move.
  email:          zhizhang5763@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.

  twitter: 
  linkedin: zhi-z-9801801a
# google_scholar: R2VUf7YAAAAJ
  google_plus: 
  github: zzh237
  facebook: 
# Analytics and webmaster tools stuff goes here
# google_analytics: UA-105680508-1
# google_verify: KFWZJ6GsxCUxQRDDrkkQJ2jgRDVUdgUbTMXXltDss84
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:



# Links to include in top navigation
# For external links add external: true
links:
  - title: Curriculum
    url: /cv/
  - title: Blog
    url: /blog/
  - title: Articles
    url: /articles/
  - title: Projects
    url: /projects/
  - title: Readings
    url: /readings/
  - title: Publications
    url: /publications/
  - title: Miscellaneous
    url: /miscellaneous/
#  - title: Tools
#    url: /tools/
#  - title: Following
#    url: /following/
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# --- Navigation bar options --- #  
# List of links in the navigation bar
navbar-links: 
  Home: "index"
  Previous Work: "previous work"
  Resume: "CV.pdf"


# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Zach Zhang
  email: "zhizhang5763@gmail.com"
  github: zzh237    # eg. daattali
  linkedin: zhi-z-9801801a

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: false
  google-plus: false
  github: true
  reddit: false
  linkedin: true
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false
  telephone: false

# Select which share links to show in posts
share-links-active:
  twitter: false
  facebook: false
  google: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "https://zhishuai.xyz"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone:    America/Chicago
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
paginate: 5
kramdown:
  input: GFM
  extensions: ["strikethrough"]

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# MathJax
mathjax: true



