title:            Zach Zhang's Website
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://zzh237.github.io
#http://localhost:5000

disqus_shortname: zzh237-github-io

# Owner/author information
owner:
  name:           Zhi Zhang
  avatar:         /author_images/zz.jpg
  bio:            Statistics, Optimization, Machine Learning
  email:          zhizhang5763@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: 
  #linkedin: zhi-z-9801801a
  #google_scholar: R2VUf7YAAAAJ
  #google_plus: 
  github: zzh237
  #facebook: dukeleimao
# Analytics and webmaster tools stuff goes here
google_analytics: UA-105680508-1
google_verify: KFWZJ6GsxCUxQRDDrkkQJ2jgRDVUdgUbTMXXltDss84
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Curriculum 
    url: /cv/
  - title: Other Work
    url: /other_work/
  - title: Referee
    url: /referee/
  #- title: Articles
    #url: /articles/
  #- title: Projects
    #url: /projects/
#   - title: Readings
#     url: /readings/
  #- title: Publications
    #url: /publications/
  #- title: Miscellaneous
    #url: /miscellaneous/
#  - title: Tools
#    url: /tools/
#  - title: Following
#    url: /following/

navbar-links: 
  Home: "index"
  Previous Work: "previous work"
  Resume: "CV.pdf"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# MathJax
mathjax: true
